version: '3.7' # We use version 3.5 syntax
services: # Here we define our service(s)
  node: # The name of the service
    container_name: ${APP_NAME}_node  # Container name
    build:
      context: docker/node
    volumes: # Volume binding
      - './:/usr/src/app'
    ports:
      - '4200:4200' # Port mapping
#    working_dir: '/usr/src/app'
#    command: "npm run start"

#  nginx: # The name of the service
#    container_name: ${APP_NAME}_nginx  # Container name
#    image: nginx:alpine
#    volumes: # Volume binding
#      - './:/usr/src/app'
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./docker/nginx/sites/:/etc/nginx/sites-available
##      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
#      - ./docker/nginx/logs:/var/log/nginx
#    ports:
#      - '4200:4200' # Port mapping
#    depends_on:
#      - node
#    command: "nginx"
